forge 'https://forgeapi.puppetlabs.com'

mod 'nsidc/nsidc_nfs',
    git: 'git@bitbucket.org:/nsidc/puppet-nsidc-nfs.git'

mod 'nsidc/nsidc_jenkins',
    git: 'git@bitbucket.org:/nsidc/puppet-nsidc-jenkins.git',
    ref: 'latest'

mod 'nsidc/nsidc_miniconda',
    git: 'git@bitbucket.org:/nsidc/puppet-nsidc-miniconda.git',
    ref: 'latest'

mod 'nsidc/nsidc_emacs',
    git: 'git@bitbucket.org:/nsidc/puppet-nsidc-emacs.git',
    ref: 'latest'

# workaround, once rtyler/jenkins releases a fix for apt 2.0 this can be removed
mod 'puppetlabs/apt', '1.8.0'
